CREATE OR REPLACE TABLE REVIEW_ANALYTICS.RAW.REVIEWS_WITH_SENTIMENT AS
SELECT *,
    SNOWFLAKE.CORTEX.SENTIMENT(REVIEWTEXT) AS AI_SENTIMENT_SCORE,
    CASE 
        WHEN SNOWFLAKE.CORTEX.SENTIMENT(REVIEWTEXT) > 0.3 THEN 'Positive'
        WHEN SNOWFLAKE.CORTEX.SENTIMENT(REVIEWTEXT) < -0.3 THEN 'Negative'
        ELSE 'Neutral'
    END AS AI_SENTIMENT_LABEL
FROM REVIEW_ANALYTICS.RAW.AMAZON_REVIEWS;
