-- Department-level summary
SELECT MAINDEPARTMENT, 
    COUNT(*) AS REVIEW_COUNT,
    ROUND(AVG(TRY_CAST(REVIEWSTAR AS FLOAT)), 2) AS AVG_STAR,
    ROUND(AVG(AI_SENTIMENT_SCORE), 3) AS AVG_SENTIMENT
FROM REVIEW_ANALYTICS.RAW.REVIEWS_WITH_SENTIMENT
WHERE TRY_CAST(REVIEWSTAR AS FLOAT) IS NOT NULL
GROUP BY MAINDEPARTMENT
ORDER BY REVIEW_COUNT DESC;

-- Star vs Sentiment mismatches
SELECT COUNT(*) AS TOTAL_MISMATCHES,
    SUM(CASE WHEN TRY_CAST(REVIEWSTAR AS FLOAT) >= 4 AND AI_SENTIMENT_LABEL = 'Negative' THEN 1 ELSE 0 END) AS HIGH_STAR_NEGATIVE,
    SUM(CASE WHEN TRY_CAST(REVIEWSTAR AS FLOAT) <= 2 AND AI_SENTIMENT_LABEL = 'Positive' THEN 1 ELSE 0 END) AS LOW_STAR_POSITIVE
FROM REVIEW_ANALYTICS.RAW.REVIEWS_WITH_SENTIMENT
WHERE TRY_CAST(REVIEWSTAR AS FLOAT) IS NOT NULL
  AND ((TRY_CAST(REVIEWSTAR AS FLOAT) >= 4 AND AI_SENTIMENT_LABEL = 'Negative')
    OR (TRY_CAST(REVIEWSTAR AS FLOAT) <= 2 AND AI_SENTIMENT_LABEL = 'Positive'));
